library(varhandle)
gcw$water <- unfactor(gcw$water)
gcw$wall <- unfactor(gcw$wall)
gcw$floor <- unfactor(gcw$floor)
gcw$toilets <- unfactor(gcw$toilets)

gcw$water[which(gcw$water=="11")] <- "11"
gcw$water[which(gcw$water=="12")] <- "12"
gcw$water[which(gcw$water=="13")] <- "13"
gcw$water[which(gcw$water=="14")] <- "14"
gcw$water[which(gcw$water=="21")] <- "21"
gcw$water[which(gcw$water=="22")] <- "22"
gcw$water[which(gcw$water=="31")] <- "31"
gcw$water[which(gcw$water=="32")] <- "32"
gcw$water[which(gcw$water=="33")] <- "33"
gcw$water[which(gcw$water=="34")] <- "34"
gcw$water[which(gcw$water=="41")] <- "41"
gcw$water[which(gcw$water=="42")] <- "42"
gcw$water[which(gcw$water=="43")] <- "43"
gcw$water[which(gcw$water=="44")] <- "44"
gcw$water[which(gcw$water=="45")] <- "45"
gcw$water[which(gcw$water=="51")] <- "51"
gcw$water[which(gcw$water=="52")] <- "52"
gcw$water[which(gcw$water=="61")] <- "61"
gcw$water[which(gcw$water=="62")] <- "62"
gcw$water[which(gcw$water=="63")] <- "63"
gcw$water[which(gcw$water=="71")] <- "71"
gcw$water[which(gcw$water=="72")] <- "72"
gcw$water[which(gcw$water=="96")] <- "96"
gcw$water[which(gcw$water=="99")] <- "99"
gcw$water[which(gcw$water=="Balli")] <- "Balli"
gcw$water[which(gcw$water=="Berkad")] <- "Berkad"
gcw$water[which(gcw$water=="Forage")] <- "borehole"
gcw$water[which(gcw$water=="borehole in yard/plot")] <- "borehole in yard/plot"
gcw$water[which(gcw$water=="Puits à pompe busé")] <- "Borehole pump well"
gcw$water[which(gcw$water=="Puits à pompe, forage")] <- "Borehole pump well"
gcw$water[which(gcw$water=="Puits a pompe/forage")] <- "Borehole pump well"
gcw$water[which(gcw$water=="Borehole with pump")] <- "Borehole with pump"
gcw$water[which(gcw$water=="bottled water")] <- "bottled water"
gcw$water[which(gcw$water=="Bottled water")] <- "bottled water"
gcw$water[which(gcw$water=="Agua embotellada/envasada")] <- "bottled water"
gcw$water[which(gcw$water=="Eau en bouteille")] <- "bottled water"
gcw$water[which(gcw$water=="cart with small tank")] <- "cart with small tank"
gcw$water[which(gcw$water=="Cart with small tank")] <- "cart with small tank"
gcw$water[which(gcw$water=="Cart with small tank / drum")] <- "cart with small tank"
gcw$water[which(gcw$water=="Cart with samll tank/drum")] <- "cart with small tank"
gcw$water[which(gcw$water=="Cart with small tank/drum")] <- "cart with small tank"
gcw$water[which(gcw$water=="Charrette avec petite citerne / tonneau")] <- "cart with small tank"
gcw$water[which(gcw$water=="container")] <- "container"
gcw$water[which(gcw$water=="dam")] <- "dam"
gcw$water[which(gcw$water=="Elevated tank, hand pump (Kharjaka)")] <- "Elevated tank, hand pump"
gcw$water[which(gcw$water=="Filtered (river, stream, dam, hafir, lake, pond, canal or rain water")] <- "Filtered (river, stream, dam, hafir, lake, pond, canal or rain water"
gcw$water[which(gcw$water=="Filtered Rainwater collection")] <- "Filtered Rainwater collection"
gcw$water[which(gcw$water=="government network")] <- "government network"
gcw$water[which(gcw$water=="gravity flow scheme")] <- "gravity flow scheme"
gcw$water[which(gcw$water=="local network")] <- "local network"
gcw$water[which(gcw$water=="Missing")] <- "NA"
gcw$water[which(gcw$water=="Manquant")] <- "NA"
gcw$water[which(gcw$water=="Puits moderne couvert")] <- "modern covered well"
gcw$water[which(gcw$water=="Puits moderne non couvert")] <- "modern uncovered well"
gcw$water[which(gcw$water=="NA")] <- "NA"
gcw$water[which(gcw$water=="Neighbor's house")] <- "neighbour's tap"
gcw$water[which(gcw$water=="Neighbor's tap")] <- "neighbour's tap"
gcw$water[which(gcw$water=="Robinet du voisin")] <- "neighbour's tap"
gcw$water[which(gcw$water=="TuberÃ�a al vecino")] <- "neighbour's tap"
gcw$water[which(gcw$water=="Tubería al vecino")] <- "neighbour's tap"
gcw$water[which(gcw$water=="neighbour's tap")] <- "neighbour's tap"
gcw$water[which(gcw$water=="open public well")] <- "open public well"
gcw$water[which(gcw$water=="open well in dwelling")] <- "open well in dwelling"
gcw$water[which(gcw$water=="open well in yard/polt")] <- "open well in yard/polt"
gcw$water[which(gcw$water=="open well with sump pump")] <- "open well with sump pump"
gcw$water[which(gcw$water=="open well without sump pump")] <- "open well without sump pump"
gcw$water[which(gcw$water=="other")] <- "other"
gcw$water[which(gcw$water=="Other")] <- "other"
gcw$water[which(gcw$water=="Autre")] <- "other"
gcw$water[which(gcw$water=="Otra")] <- "other"
gcw$water[which(gcw$water=="Ource non protegee")] <- "other non protected"
gcw$water[which(gcw$water=="piped from the neighbor")] <- "piped from the neighbor"
gcw$water[which(gcw$water=="Piped into compound")] <- "Piped into compound, yard or plot"
gcw$water[which(gcw$water=="Piped into compound, yard or plot")] <- "Piped into compound, yard or plot"
gcw$water[which(gcw$water=="Robinet dans la concession, cour ou parcelle")] <- "Piped into compound, yard or plot"
gcw$water[which(gcw$water=="Robinet dans quartier, cour ou parcelle")] <- "Piped into compound, yard or plot"
gcw$water[which(gcw$water=="TuberÃ�a dentro del terreno, patio o lote")] <- "Piped into compound, yard or plot"
gcw$water[which(gcw$water=="Tubería dentro del terreno, patio o lote")] <- "Piped into compound, yard or plot"
gcw$water[which(gcw$water=="piped into dwelling")] <- "piped into dwelling"
gcw$water[which(gcw$water=="Piped into dwelling")] <- "piped into dwelling"
gcw$water[which(gcw$water=="Eau de robinet dns le logement")] <- "piped into dwelling"
gcw$water[which(gcw$water=="Robinet dans le logement")] <- "piped into dwelling"
gcw$water[which(gcw$water=="TuberÃ�a dentro de la vivienda")] <- "piped into dwelling"
gcw$water[which(gcw$water=="Tubería dentro de la vivienda")] <- "piped into dwelling"
gcw$water[which(gcw$water=="Piped into dwelling from central system")] <- "Piped into dwelling from central system"
gcw$water[which(gcw$water=="Piped into dwelling from individual system")] <- "Piped into dwelling from individual system"
gcw$water[which(gcw$water=="Piped outside dwelling but within buikding")] <- "Piped outside dwelling but within building"
gcw$water[which(gcw$water=="Piped to neighbor")] <- "Piped to neighbor"
gcw$water[which(gcw$water=="Piped to neighbour")] <- "Piped to neighbor"
gcw$water[which(gcw$water=="piped to yard/plot")] <- "piped to yard/plot"
gcw$water[which(gcw$water=="Piped to yard/plot")] <- "piped to yard/plot"
gcw$water[which(gcw$water=="Dans la cour/parcelle")] <- "piped to yard/plot"
gcw$water[which(gcw$water=="Piped into yard or plot")] <- "piped to yard/plot"
gcw$water[which(gcw$water=="piped water from rural system")] <- "piped water from rural system"
gcw$water[which(gcw$water=="piped water from utility company")] <- "piped water from utility company"
gcw$water[which(gcw$water=="pond/lake")] <- "pond/lake"
gcw$water[which(gcw$water=="Private piped into dwelling")] <- "Private piped into dwelling"
gcw$water[which(gcw$water=="Private piped into yard")] <- "Private piped into yard"
gcw$water[which(gcw$water=="protected public well")] <- "protected public well"
gcw$water[which(gcw$water=="protected spring")] <- "protected spring"
gcw$water[which(gcw$water=="Protected spring")] <- "protected spring"
gcw$water[which(gcw$water=="Manantial o pozo surgente protegido")] <- "protected spring"
gcw$water[which(gcw$water=="Manantial protegido")] <- "protected spring"
gcw$water[which(gcw$water=="Source protegee")] <- "protected spring"
gcw$water[which(gcw$water=="Source protégée")] <- "protected spring"
gcw$water[which(gcw$water=="protected well")] <- "protected well"
gcw$water[which(gcw$water=="Protected well")] <- "protected well"
gcw$water[which(gcw$water=="Puits protégé")] <- "protected well"
gcw$water[which(gcw$water=="Pozo protegido")] <- "protected well"
gcw$water[which(gcw$water=="Puits protege")] <- "protected well"
gcw$water[which(gcw$water=="protected well in dwelling")] <- "protected well in dwelling"
gcw$water[which(gcw$water=="protected well in yard/polt")] <- "protected well in yard/polt"
gcw$water[which(gcw$water=="Protected well/kariaz")] <- "Protected well/kariaz"
gcw$water[which(gcw$water=="Protected/covered well")] <- "Protected/covered well"
gcw$water[which(gcw$water=="public borehole")] <- "public borehole"
gcw$water[which(gcw$water=="Robinet public/borne fontaine")] <- "Public faucet"
gcw$water[which(gcw$water=="Public outdoor tap")] <- "Public outdoor tap"
gcw$water[which(gcw$water=="public tap")] <- "public tap"
gcw$water[which(gcw$water=="Public tap / standpipe")] <- "public tap/standpipe"
gcw$water[which(gcw$water=="Canilla o grifo pÃºblico")] <- "public tap/standpipe"
gcw$water[which(gcw$water=="public tap/standpipe")] <- "public tap/standpipe"
gcw$water[which(gcw$water=="Public tap/standpipe")] <- "public tap/standpipe"
gcw$water[which(gcw$water=="Robinet public / borne fontaine")] <- "public tap/standpipe"
gcw$water[which(gcw$water=="Llave/grifo público")] <- "public tap/standpipe"
gcw$water[which(gcw$water=="public to neighborhood")] <- "public to neighborhood"
gcw$water[which(gcw$water=="Public water kiosk connected with central system")] <- "Public water kiosk connected with central system"
gcw$water[which(gcw$water=="Public well")] <- "Public well"
gcw$water[which(gcw$water=="rain water")] <- "rainwater"
gcw$water[which(gcw$water=="rainwater")] <- "rainwater"
gcw$water[which(gcw$water=="Rainwater")] <- "rainwater"
gcw$water[which(gcw$water=="Eau de pluie")] <- "rainwater"
gcw$water[which(gcw$water=="Eau de pluie/Majel/Fasquia")] <- "rainwater"
gcw$water[which(gcw$water=="Recogen agua de lluvia")] <- "rainwater"
gcw$water[which(gcw$water=="Rainwater collection")] <- "rainwater"
gcw$water[which(gcw$water=="refill water")] <- "refill water"
gcw$water[which(gcw$water=="Reverse osmosis (RO)")] <- "Reverse osmosis (RO)"
gcw$water[which(gcw$water=="River/dam/lake/ponds/stream/canal/irirgation channel")] <- "river/dam/lake/ponds/stream/canal/irrigation channel"
gcw$water[which(gcw$water=="river/dam/lake/ponds/stream/canal/irirgation channel")] <- "river/dam/lake/ponds/stream/canal/irrigation channel"
gcw$water[which(gcw$water=="river/dam/lake/ponds/stream/canal/irrigation channel")] <- "river/dam/lake/ponds/stream/canal/irrigation channel"
gcw$water[which(gcw$water=="River/dam/lake/ponds/stream/canal/irrigation channel")] <- "river/dam/lake/ponds/stream/canal/irrigation channel"
gcw$water[which(gcw$water=="river/stream")] <- "river/stream"
gcw$water[which(gcw$water=="river/stream/spring")] <- "river/stream/spring"
gcw$water[which(gcw$water=="Roof top")] <- "Roof top"
gcw$water[which(gcw$water=="Semi-protected well")] <- "Semi-protected well"
gcw$water[which(gcw$water=="spring")] <- "spring"
gcw$water[which(gcw$water=="Spring")] <- "spring"
gcw$water[which(gcw$water=="Agua de superficie(rÃ�o, arroyo, represa, lago, estanque, canal, canal de irrigaciÃ³n)")] <- "surface water"
gcw$water[which(gcw$water=="Eau de surface")] <- "surface water"
gcw$water[which(gcw$water=="Surface water")] <- "surface water"
gcw$water[which(gcw$water=="Surface water (river, stream, dam, lake, pond, canal, irrigation channel)")] <- "Surface water (river, stream, dam, lake, pond, canal, irrigation channel)"
gcw$water[which(gcw$water=="Surface water (river,stream, dam, lake,pond,canal,irrigation channel)")] <- "Surface water (river, stream, dam, lake, pond, canal, irrigation channel)"
gcw$water[which(gcw$water=="Agua de superficie(río, arroyo, represa, lago, estanque, canal, canal de irrigación)")] <- "surface water (river, stream, dam, lake, pond, canal, irrigation channel)"
gcw$water[which(gcw$water=="Eau de surface (rivi?re, fleuve, barrage, lac, mare, canal, canal d'irrigation)")] <- "surface water (river, stream, dam, lake, pond, canal, irrigation channel)"
gcw$water[which(gcw$water=="Eau de surface (rivière, fleuve, barrage, lac, mare, canal, canal d'irrigation)")] <- "surface water (river, stream, dam, lake, pond, canal, irrigation channel)"
gcw$water[which(gcw$water=="surface water protected")] <- "surface water protected"
gcw$water[which(gcw$water=="surface water unprotected")] <- "surface water unprotected"
gcw$water[which(gcw$water=="Camion-citerne")] <- "tanker truck"
gcw$water[which(gcw$water=="tanker truck")] <- "tanker truck"
gcw$water[which(gcw$water=="Tanker truck")] <- "tanker truck"
gcw$water[which(gcw$water=="Tanker-truck")] <- "tanker truck"
gcw$water[which(gcw$water=="Carrotanque / camiÃ³n cisterna")] <- "tanker truck"
gcw$water[which(gcw$water=="Carrotanque / camión cisterna")] <- "tanker truck"
gcw$water[which(gcw$water=="Tanker-truck: Water truck")] <- "tanker truck"
gcw$water[which(gcw$water=="Tanker-truck from protected sources")] <- "Tanker-truck from protected sources"
gcw$water[which(gcw$water=="Tanker-truck from unkown sources")] <- "Tanker-truck from unkown sources"
gcw$water[which(gcw$water=="Tanker-truck from unprotected sources")] <- "Tanker-truck from unprotected sources"
gcw$water[which(gcw$water=="Tanker-truck: Public water kiosk")] <- "Tanker-truck: Public water kiosk"
gcw$water[which(gcw$water=="Puits traditionnel couvert")] <- "traditional covered well "
gcw$water[which(gcw$water=="Puits traditionnel non couvert")] <- "traditional uncovered well"
gcw$water[which(gcw$water=="tube well or borehole")] <- "tube well or borehole"
gcw$water[which(gcw$water=="Tube well or borehole")] <- "tube well or borehole"
gcw$water[which(gcw$water=="Tube well, Borehole")] <- "tube well or borehole"
gcw$water[which(gcw$water=="Tubewell/borehole")] <- "tube well or borehole"
gcw$water[which(gcw$water=="Unfiltered (river, stream, dam, hafir, lake, pond, canal or rain) water")] <- "Unfiltered (river, stream, dam, hafir, lake, pond, canal or rain) water"
gcw$water[which(gcw$water=="UnFiltered Rainwater collection")] <- "UnFiltered Rainwater collection"
gcw$water[which(gcw$water=="unprotected spring")] <- "unprotected spring"
gcw$water[which(gcw$water=="Unprotected spring")] <- "unprotected spring"
gcw$water[which(gcw$water=="Manantial no protegido")] <- "unprotected spring"
gcw$water[which(gcw$water=="Manantial o pozo surgente no protegido")] <- "unprotected spring"
gcw$water[which(gcw$water=="Source non protegee")] <- "unprotected spring"
gcw$water[which(gcw$water=="Source non protégée")] <- "unprotected spring"
gcw$water[which(gcw$water=="Puits non protégé")] <- "unprotected well"
gcw$water[which(gcw$water=="unprotected well")] <- "unprotected well"
gcw$water[which(gcw$water=="Unprotected well")] <- "unprotected well"
gcw$water[which(gcw$water=="Pozo no protegido")] <- "unprotected well"
gcw$water[which(gcw$water=="Puits non protege")] <- "unprotected well"
gcw$water[which(gcw$water=="Unprotected well/kariaz")] <- "Unprotected well/kariaz"
gcw$water[which(gcw$water=="vendor")] <- "vendor"
gcw$water[which(gcw$water=="water in drums/big cans")] <- "water in drums/big cans"
gcw$water[which(gcw$water=="sachet water")] <- "water in plastic bag"
gcw$water[which(gcw$water=="water in plastic bag")] <- "water in plastic bag"
gcw$water[which(gcw$water=="Water transported by tankers/carts from improved source")] <- "Water transported by tankers/carts from improved source"
gcw$water[which(gcw$water=="Water transported by tankers/carts from unimproved source")] <- "Water transported by tankers/carts from unimproved source"
gcw$water[which(gcw$water=="Water vendor")] <- "Water vendor"
gcw$water[which(gcw$water=="Water yard/hand pump")] <- "Water yard/hand pump"
gcw$water[which(gcw$water=="well")] <- "well"
gcw$water[which(gcw$water=="Puits à pompe non busé")] <- "well"
gcw$water[which(gcw$water=="Well inside dwelling")] <- "Well inside dwelling"
gcw$water[which(gcw$water=="Puits ou forage ? PMH")] <- "well or borehole PMH"
gcw$water[which(gcw$water=="Pozo con tuberÃ�a")] <- "well with pipe"
gcw$water[which(gcw$water=="Pozo con tubería")] <- "well with pipe"

gcw$wall[which(gcw$wall=="11")] <- "11"
gcw$wall[which(gcw$wall=="12")] <- "12"
gcw$wall[which(gcw$wall=="13")] <- "13"
gcw$wall[which(gcw$wall=="14")] <- "14"
gcw$wall[which(gcw$wall=="15")] <- "15"
gcw$wall[which(gcw$wall=="21")] <- "21"
gcw$wall[which(gcw$wall=="22")] <- "22"
gcw$wall[which(gcw$wall=="23")] <- "23"
gcw$wall[which(gcw$wall=="24")] <- "24"
gcw$wall[which(gcw$wall=="25")] <- "25"
gcw$wall[which(gcw$wall=="26")] <- "26"
gcw$wall[which(gcw$wall=="27")] <- "27"
gcw$wall[which(gcw$wall=="28")] <- "28"
gcw$wall[which(gcw$wall=="31")] <- "31"
gcw$wall[which(gcw$wall=="32")] <- "32"
gcw$wall[which(gcw$wall=="33")] <- "33"
gcw$wall[which(gcw$wall=="34")] <- "34"
gcw$wall[which(gcw$wall=="35")] <- "35"
gcw$wall[which(gcw$wall=="36")] <- "36"
gcw$wall[which(gcw$wall=="37")] <- "37"
gcw$wall[which(gcw$wall=="38")] <- "38"
gcw$wall[which(gcw$wall=="39")] <- "39"
gcw$wall[which(gcw$wall=="41")] <- "41"
gcw$wall[which(gcw$wall=="42")] <- "42"
gcw$wall[which(gcw$wall=="43")] <- "43"
gcw$wall[which(gcw$wall=="44")] <- "44"
gcw$wall[which(gcw$wall=="96")] <- "96"
gcw$wall[which(gcw$wall=="99")] <- "99"
gcw$wall[which(gcw$wall=="Adobe")] <- "adobe"
gcw$wall[which(gcw$wall=="adobe (mud bricks)")] <- "adobe"
gcw$wall[which(gcw$wall=="adobe covered")] <- "adobe (covered)"
gcw$wall[which(gcw$wall=="Adobe cubierto")] <- "adobe (covered)"
gcw$wall[which(gcw$wall=="Adobe non recouvert")] <- "adobe (not-covered)"
gcw$wall[which(gcw$wall=="adobe not covered/bamboo/wood with mud")] <- "adobe (not-covered)"
gcw$wall[which(gcw$wall=="Adobe on couvert")] <- "adobe (covered)"
gcw$wall[which(gcw$wall=="Adobe recouvert")] <- "adobe (covered)"
gcw$wall[which(gcw$wall=="asbestos, wood, zinc")] <- "asbestos, wood, zinc"
gcw$wall[which(gcw$wall=="Autre")] <- "other"
gcw$wall[which(gcw$wall=="Autre (précisez)")] <- "other"
gcw$wall[which(gcw$wall=="Autres")] <- "other"
gcw$wall[which(gcw$wall=="Bambo with mud")] <- "bamboo with mud"
gcw$wall[which(gcw$wall=="bamboo")] <- "bamboo"
gcw$wall[which(gcw$wall=="Bamboo")] <- "bamboo"
gcw$wall[which(gcw$wall=="bamboo / pole with mud")] <- "bamboo with mud"
gcw$wall[which(gcw$wall=="Bamboo lattice")] <- "bamboo"
gcw$wall[which(gcw$wall=="Bamboo mat")] <- "bamboo"
gcw$wall[which(gcw$wall=="bamboo with mud")] <- "bamboo with mud"
gcw$wall[which(gcw$wall=="Bamboo with mud")] <- "bamboo with mud"
gcw$wall[which(gcw$wall=="bamboo with mud plaster")] <- "bamboo with mud"
gcw$wall[which(gcw$wall=="bamboo with mud/clay/dung")] <- "bamboo with mud"
gcw$wall[which(gcw$wall=="bamboo without plaster")] <- "bamboo"
gcw$wall[which(gcw$wall=="bamboo(guadua), straw, other plants")] <- "bamboo"
gcw$wall[which(gcw$wall=="Bamboo/Bamboo with dry leaf")] <- "bamboo"
gcw$wall[which(gcw$wall=="bamboo/tree trunks with mud")] <- "bamboo with mud"
gcw$wall[which(gcw$wall=="Bamboo/Wood with mud")] <- "bamboo with mud"
gcw$wall[which(gcw$wall=="Bambou avec boue")] <- "bamboo with mud"
gcw$wall[which(gcw$wall=="Bambú con barro")] <- "bamboo with mud"
gcw$wall[which(gcw$wall=="Bambu with mud")] <- "bamboo with mud"
gcw$wall[which(gcw$wall=="Beton")] <- "concrete"
gcw$wall[which(gcw$wall=="block/cements/bricks")] <- "cement blocks"
gcw$wall[which(gcw$wall=="blocks of clay")] <- "clay blocks"
gcw$wall[which(gcw$wall=="Blocs de ciment")] <- "cement blocks"
gcw$wall[which(gcw$wall=="Bloques de cemento")] <- "cement blocks"
gcw$wall[which(gcw$wall=="Bois de recuperation")] <- "reused wood"
gcw$wall[which(gcw$wall=="Bois/metal de recuperation")] <- "reused wood/metal"
gcw$wall[which(gcw$wall=="brick")] <- "bricks"
gcw$wall[which(gcw$wall=="Brick/cement blocks")] <- "cement blocks"
gcw$wall[which(gcw$wall=="bricks")] <- "bricks"
gcw$wall[which(gcw$wall=="Bricks")] <- "bricks"
gcw$wall[which(gcw$wall=="bricks/polished wood/premanufactured material")] <- "bricks/polished wood/premanufactured material"
gcw$wall[which(gcw$wall=="Briques")] <- "bricks"
gcw$wall[which(gcw$wall=="Briques decouvertes")] <- "uncovered bricks"
gcw$wall[which(gcw$wall=="burnt bricks")] <- "burnt bricks"
gcw$wall[which(gcw$wall=="burnt bricks with cement")] <- "burnt bricks"
gcw$wall[which(gcw$wall=="CaÃ±a / Troncos")] <- "canes/palms/trunks"
gcw$wall[which(gcw$wall=="CaÃ±a o ramas con barro")] <- "canes/palms/trunks"
gcw$wall[which(gcw$wall=="cane / palm / trunks")] <- "canes/palms/trunks"
gcw$wall[which(gcw$wall=="Cane / palm / trunks")] <- "canes/palms/trunks"
gcw$wall[which(gcw$wall=="Cane / Palm / Trunks")] <- "canes/palms/trunks"
gcw$wall[which(gcw$wall=="Cane, straw and mud")] <- "canes/palms/trunks"
gcw$wall[which(gcw$wall=="cane/palm/trunks")] <- "canes/palms/trunks"
gcw$wall[which(gcw$wall=="Cane/palm/trunks")] <- "canes/palms/trunks"
gcw$wall[which(gcw$wall=="Cane/Palm/Trunks")] <- "canes/palms/trunks"
gcw$wall[which(gcw$wall=="Cane/Palm/Trunks/Bamboo")] <- "canes/palms/trunks"
gcw$wall[which(gcw$wall=="cane/tree trunks")] <- "canes/palms/trunks"
gcw$wall[which(gcw$wall=="Cane/Trunks")] <- "canes/palms/trunks"
gcw$wall[which(gcw$wall=="canes/palms/trunks")] <- "canes/palms/trunks"
gcw$wall[which(gcw$wall=="Canne / Palmes / Troncs")] <- "canes/palms/trunks"
gcw$wall[which(gcw$wall=="Canne/palmes/tronc")] <- "canes/palms/trunks"
gcw$wall[which(gcw$wall=="cardboard")] <- "cardboard"
gcw$wall[which(gcw$wall=="Cardboard")] <- "cardboard"
gcw$wall[which(gcw$wall=="Cardboard/ Carton")] <- "cardboard"
gcw$wall[which(gcw$wall=="cardboard/plastic")] <- "cardboard"
gcw$wall[which(gcw$wall=="CartÃ³n")] <- "cardboard"
gcw$wall[which(gcw$wall=="Carton")] <- "cardboard"
gcw$wall[which(gcw$wall=="Cartón")] <- "cardboard"
gcw$wall[which(gcw$wall=="Carton/Cardboard")] <- "cardboard"
gcw$wall[which(gcw$wall=="carved stone")] <- "cut stone"
gcw$wall[which(gcw$wall=="cement")] <- "cement"
gcw$wall[which(gcw$wall=="Cement")] <- "cement"
gcw$wall[which(gcw$wall=="cement blocks")] <- "cement blocks"
gcw$wall[which(gcw$wall=="Cement blocks")] <- "cement blocks"
gcw$wall[which(gcw$wall=="cement blocks/cement stones")] <- "cement blocks"
gcw$wall[which(gcw$wall=="cement bricks")] <- "cement blocks"
gcw$wall[which(gcw$wall=="Cement/RCC wall")] <- "cement blocks"
gcw$wall[which(gcw$wall=="Cemento")] <- "cement"
gcw$wall[which(gcw$wall=="Chapa o Metal")] <- "metal"
gcw$wall[which(gcw$wall=="Ciment")] <- "cement"
gcw$wall[which(gcw$wall=="Clay")] <- "clay blocks"
gcw$wall[which(gcw$wall=="Clay blocs")] <- "clay blocks"
gcw$wall[which(gcw$wall=="Clay bricks")] <- "clay blocks"
gcw$wall[which(gcw$wall=="cloth, wool")] <- "cloth"
gcw$wall[which(gcw$wall=="Cloth/Matting")] <- "cloth"
gcw$wall[which(gcw$wall=="Coconut leaves/thatches")] <- "straw / mats"
gcw$wall[which(gcw$wall=="Compressed wood")] <- "plywood"
gcw$wall[which(gcw$wall=="concrete")] <- "concrete"
gcw$wall[which(gcw$wall=="Concrete")] <- "concrete"
gcw$wall[which(gcw$wall=="Concrete blocks")] <- "concrete blocks"
gcw$wall[which(gcw$wall=="Concrete board")] <- "concrete"
gcw$wall[which(gcw$wall=="concrete or stone blocks")] <- "concrete blocks"
gcw$wall[which(gcw$wall=="Construction bricks")] <- "bricks"
gcw$wall[which(gcw$wall=="Contre-plaque")] <- "plywood"
gcw$wall[which(gcw$wall=="corrugated iron/zinc")] <- "metal"
gcw$wall[which(gcw$wall=="covered adobe")] <- "covered adobe"
gcw$wall[which(gcw$wall=="Covered adobe")] <- "covered adobe"
gcw$wall[which(gcw$wall=="Covered adobe (plastered mud bricks)")] <- "covered adobe"
gcw$wall[which(gcw$wall=="cut stone")] <- "cut stone"
gcw$wall[which(gcw$wall=="cut stone and concrete")] <- "cut stone"
gcw$wall[which(gcw$wall=="Decorative bricks")] <- "bricks"
gcw$wall[which(gcw$wall=="dirt")] <- "dirt"
gcw$wall[which(gcw$wall=="Dirt")] <- "dirt"
gcw$wall[which(gcw$wall=="Dirt/Tapia")] <- "dirt"
gcw$wall[which(gcw$wall=="dung/mud/sod")] <- "dirt"
gcw$wall[which(gcw$wall=="Earth/sand/clay")] <- "dirt"
gcw$wall[which(gcw$wall=="Estera")] <- "dirt"
gcw$wall[which(gcw$wall=="Facade (for example, cement lime mortar)")] <- "facade"
gcw$wall[which(gcw$wall=="Galvanised Iron/Aluzinc")] <- "metal"
gcw$wall[which(gcw$wall=="Galvanized iron/Aluzinc")] <- "metal"
gcw$wall[which(gcw$wall=="Grass")] <- "grass"
gcw$wall[which(gcw$wall=="hair wool cloth")] <- "cloth"
gcw$wall[which(gcw$wall=="Half cement, half wood")] <- "cement and wood"
gcw$wall[which(gcw$wall=="Hallow Clay Blocks")] <- "clay blocks"
gcw$wall[which(gcw$wall=="Hey and mud")] <- "straw with mud"
gcw$wall[which(gcw$wall=="Hollow clay blocks")] <- "clay blocks"
gcw$wall[which(gcw$wall=="Hollow clay/Concrete blocks (plastered)")] <- "clay blocks"
gcw$wall[which(gcw$wall=="iron sheets")] <- "metal"
gcw$wall[which(gcw$wall=="Ladrillo")] <- "bricks"
gcw$wall[which(gcw$wall=="Limestone / cement")] <- "cement"
gcw$wall[which(gcw$wall=="Limestone bloc")] <- "cement blocks"
gcw$wall[which(gcw$wall=="local adobe")] <- "adobe"
gcw$wall[which(gcw$wall=="Madera compensada (hardboard-mdf)")] <- "plywood"
gcw$wall[which(gcw$wall=="Madera reutilizada")] <- "reused wood"
gcw$wall[which(gcw$wall=="Manquant")] <- "NA"
gcw$wall[which(gcw$wall=="Material de desecho(latas viejas, sacos, plàstico, etc)")] <- "waste material"
gcw$wall[which(gcw$wall=="metal")] <- "metal"
gcw$wall[which(gcw$wall=="Metal")] <- "metal"
gcw$wall[which(gcw$wall=="Metal/jenco")] <- "metal"
gcw$wall[which(gcw$wall=="Missing")] <- "NA"
gcw$wall[which(gcw$wall=="Mottes de terre")] <- "dirt"
gcw$wall[which(gcw$wall=="mud")] <- "dirt"
gcw$wall[which(gcw$wall=="Mud")] <- "dirt"
gcw$wall[which(gcw$wall=="Mud (Pole and Dugger)")] <- "sticks and mud"
gcw$wall[which(gcw$wall=="mud and poles")] <- "sticks and mud"
gcw$wall[which(gcw$wall=="Mud blocks")] <- "mud blocks"
gcw$wall[which(gcw$wall=="mud bricks")] <- "mud blocks"
gcw$wall[which(gcw$wall=="mud bricks with stones")] <- "mud blocks"
gcw$wall[which(gcw$wall=="Mud or mud bricks")] <- "mud blocks"
gcw$wall[which(gcw$wall=="Mud wall/Bamboo with mud")] <- "bamboo with mud"
gcw$wall[which(gcw$wall=="NA")] <- "NA"
gcw$wall[which(gcw$wall=="No hay paredes")] <- "no walls"
gcw$wall[which(gcw$wall=="No walls")] <- "no walls"
gcw$wall[which(gcw$wall=="no walls")] <- "no walls"
gcw$wall[which(gcw$wall=="other")] <- "other"
gcw$wall[which(gcw$wall=="Other")] <- "other"
gcw$wall[which(gcw$wall=="OTHER")] <- "other"
gcw$wall[which(gcw$wall=="Otro")] <- "other"
gcw$wall[which(gcw$wall=="palm")] <- "canes/palms/trunks"
gcw$wall[which(gcw$wall=="palm leave (yagua)")] <- "canes/palms/trunks"
gcw$wall[which(gcw$wall=="palm/bamboo/thatch")] <- "canes/palms/trunks"
gcw$wall[which(gcw$wall=="Palmetto/Wildcane/Sticks")] <- "canes/palms/trunks"
gcw$wall[which(gcw$wall=="Pas de mur")] <- "no walls"
gcw$wall[which(gcw$wall=="Pas de murs")] <- "no walls"
gcw$wall[which(gcw$wall=="Piedra con barro")] <- "stone with mud"
gcw$wall[which(gcw$wall=="Piedra con limo/cemento")] <- "stone with cement"
gcw$wall[which(gcw$wall=="Pierre avec boue")] <- "stone with mud"
gcw$wall[which(gcw$wall=="Pierre avec chaux/ciment")] <- "stone with cement"
gcw$wall[which(gcw$wall=="Pierre avec ciment")] <- "stone with cement"
gcw$wall[which(gcw$wall=="plain stone")] <- "stone"
gcw$wall[which(gcw$wall=="Planche de bois/shingles")] <- "wood planks / shingles"
gcw$wall[which(gcw$wall=="Planches en bois / de shingles")] <- "wood planks / shingles"
gcw$wall[which(gcw$wall=="planks")] <- "wood planks / shingles"
gcw$wall[which(gcw$wall=="Plaster")] <- "plaster"
gcw$wall[which(gcw$wall=="Plaster walls")] <- "plaster"
gcw$wall[which(gcw$wall=="Plastered concrete blocks")] <- "concrete blocks"
gcw$wall[which(gcw$wall=="Plastic")] <- "plastic"
gcw$wall[which(gcw$wall=="plywood")] <- "plywood"
gcw$wall[which(gcw$wall=="Plywood")] <- "plywood"
gcw$wall[which(gcw$wall=="PlyWood")] <- "plywood"
gcw$wall[which(gcw$wall=="Plywood (Off cuts)")] <- "reused wood"
gcw$wall[which(gcw$wall=="Prefabricado")] <- "prefabricated"
gcw$wall[which(gcw$wall=="prefabricated material")] <- "prefabricated"
gcw$wall[which(gcw$wall=="Rammed earth")] <- "dirt"
gcw$wall[which(gcw$wall=="Reed")] <- "canes/palms/trunks"
gcw$wall[which(gcw$wall=="reused wood")] <- "reused wood"
gcw$wall[which(gcw$wall=="Reused wood")] <- "reused wood"
gcw$wall[which(gcw$wall=="Reused wood (fibreboard)")] <- "reused wood"
gcw$wall[which(gcw$wall=="Revoque o estucado")] <- "plaster"
gcw$wall[which(gcw$wall=="Rustic mats")] <- "straw / mats"
gcw$wall[which(gcw$wall=="Shells (Casca)")] <- "shells"
gcw$wall[which(gcw$wall=="shingle (tejamanil)")] <- "wood planks / shingles"
gcw$wall[which(gcw$wall=="sod")] <- "dirt"
gcw$wall[which(gcw$wall=="Soil block(Taboq)")] <- "dirt"
gcw$wall[which(gcw$wall=="Stick-Mud")] <- "sticks and mud"
gcw$wall[which(gcw$wall=="Sticks (paus maticados)")] <- "sticks and mud"
gcw$wall[which(gcw$wall=="sticks and mud")] <- "sticks and mud"
gcw$wall[which(gcw$wall=="sticks with mud/clay/dung")] <- "sticks and mud"
gcw$wall[which(gcw$wall=="Sticks/palm/trunks")] <- "canes/palms/trunks"
gcw$wall[which(gcw$wall=="Stone with cal or cement")] <- "stone with cement"
gcw$wall[which(gcw$wall=="Stone with cement")] <- "stone with cement"
gcw$wall[which(gcw$wall=="stone with lime / cement")] <- "stone with cement"
gcw$wall[which(gcw$wall=="Stone with lime / cement")] <- "stone with cement"
gcw$wall[which(gcw$wall=="Stone with lime/ cement")] <- "stone with cement"
gcw$wall[which(gcw$wall=="stone with lime/cement")] <- "stone with cement"
gcw$wall[which(gcw$wall=="Stone with lime/cement")] <- "stone with cement"
gcw$wall[which(gcw$wall=="Stone with Mortar")] <- "stone with cement"
gcw$wall[which(gcw$wall=="Stone with mortar")] <- "stone with cement"
gcw$wall[which(gcw$wall=="stone with mud")] <- "stone with mud"
gcw$wall[which(gcw$wall=="Stone with mud")] <- "stone with mud"
gcw$wall[which(gcw$wall=="straw /mats")] <- "straw / mats"
gcw$wall[which(gcw$wall=="straw with mud")] <- "straw with mud"
gcw$wall[which(gcw$wall=="straw, cane")] <- "straw / mats"
gcw$wall[which(gcw$wall=="Stucco")] <- "plaster"
gcw$wall[which(gcw$wall=="Tablones de madera")] <- "wood planks / shingles"
gcw$wall[which(gcw$wall=="Tablones de madera/compensados")] <- "wood planks / shingles"
gcw$wall[which(gcw$wall=="thatched/straw")] <- "straw / mats"
gcw$wall[which(gcw$wall=="Tierra")] <- "dirt"
gcw$wall[which(gcw$wall=="Tierra apisonada")] <- "dirt"
gcw$wall[which(gcw$wall=="tin")] <- "tin"
gcw$wall[which(gcw$wall=="Tin/ cardborad/ paper/ bags")] <- "waste material"
gcw$wall[which(gcw$wall=="unburnt bricks")] <- "unburnt bricks"
gcw$wall[which(gcw$wall=="unburnt bricks with mud")] <- "unburt bricks with mud"
gcw$wall[which(gcw$wall=="unburnt bricks with plaster")] <- "unburnt bricks with plaster"
gcw$wall[which(gcw$wall=="uncovered adobe")] <- "uncovered adobe"
gcw$wall[which(gcw$wall=="Uncovered adobe")] <- "uncovered adobe"
gcw$wall[which(gcw$wall=="Uncovered adobe (mud bricks)")] <- "uncovered adobe"
gcw$wall[which(gcw$wall=="used wood")] <- "reused wood"
gcw$wall[which(gcw$wall=="waste materials")] <- "waste material"
gcw$wall[which(gcw$wall=="without walls")] <- "no walls"
gcw$wall[which(gcw$wall=="Wod planks, shingles, logs")] <- "wood planks / shingles"
gcw$wall[which(gcw$wall=="wood")] <- "wood"
gcw$wall[which(gcw$wall=="Wood")] <- "wood"
gcw$wall[which(gcw$wall=="Wood (e.g. Cedar)")] <- "wood"
gcw$wall[which(gcw$wall=="Wood (eg cedar)")] <- "wood"
gcw$wall[which(gcw$wall=="Wood and concrete")] <- "wood and concrete"
gcw$wall[which(gcw$wall=="wood planks")] <- "wood planks / shingles"
gcw$wall[which(gcw$wall=="Wood planks")] <- "wood planks / shingles"
gcw$wall[which(gcw$wall=="wood planks / shingles")] <- "wood planks / shingles"
gcw$wall[which(gcw$wall=="Wood planks / shingles")] <- "wood planks / shingles"
gcw$wall[which(gcw$wall=="wood planks/shingles")] <- "wood planks / shingles"
gcw$wall[which(gcw$wall=="Wood planks/shingles")] <- "wood planks / shingles"
gcw$wall[which(gcw$wall=="wood planks/shingles/metal/corrugated")] <- "wood planks / shingles"
gcw$wall[which(gcw$wall=="wood stem")] <- "wood"
gcw$wall[which(gcw$wall=="Wood with mud")] <- "wood with mud"
gcw$wall[which(gcw$wall=="Wood/ metal planks")] <- "wood / metal planks"
gcw$wall[which(gcw$wall=="wooden plank")] <- "wood planks / shingles"
gcw$wall[which(gcw$wall=="woven bamboo")] <- "bamboo"
gcw$wall[which(gcw$wall=="Zinc")] <- "metal"
gcw$wall[which(gcw$wall=="zinc, canvas, plastics")] <- "metal"
gcw$wall[which(gcw$wall=="Zócalo (cemento con madera o fibrocemento)")] <- "cement"

gcw$floor[which(gcw$floor=="11")] <- "11"
gcw$floor[which(gcw$floor=="12")] <- "12"
gcw$floor[which(gcw$floor=="13")] <- "13"
gcw$floor[which(gcw$floor=="21")] <- "21"
gcw$floor[which(gcw$floor=="22")] <- "22"
gcw$floor[which(gcw$floor=="23")] <- "23"
gcw$floor[which(gcw$floor=="24")] <- "24"
gcw$floor[which(gcw$floor=="31")] <- "31"
gcw$floor[which(gcw$floor=="32")] <- "32"
gcw$floor[which(gcw$floor=="33")] <- "33"
gcw$floor[which(gcw$floor=="34")] <- "34"
gcw$floor[which(gcw$floor=="35")] <- "35"
gcw$floor[which(gcw$floor=="36")] <- "36"
gcw$floor[which(gcw$floor=="37")] <- "37"
gcw$floor[which(gcw$floor=="38")] <- "38"
gcw$floor[which(gcw$floor=="39")] <- "39"
gcw$floor[which(gcw$floor=="96")] <- "96"
gcw$floor[which(gcw$floor=="99")] <- "99"
gcw$floor[which(gcw$floor=="Adobe")] <- "adobe"
gcw$floor[which(gcw$floor=="Alfombra")] <- "carpet"
gcw$floor[which(gcw$floor=="Asphlat tiles/vynil")] <- "tile / vinyl"
gcw$floor[which(gcw$floor=="Autre")] <- "other"
gcw$floor[which(gcw$floor=="Autres")] <- "other"
gcw$floor[which(gcw$floor=="bamboo")] <- "palm / bamboo"
gcw$floor[which(gcw$floor=="Bamboo")] <- "palm / bamboo"
gcw$floor[which(gcw$floor=="Bouse")] <- "dung"
gcw$floor[which(gcw$floor=="Brick red (Dfrp)")] <- "bricks"
gcw$floor[which(gcw$floor=="bricks")] <- "bricks"
gcw$floor[which(gcw$floor=="broken bricks")] <- "broken bricks"
gcw$floor[which(gcw$floor=="carpet")] <- "carpet"
gcw$floor[which(gcw$floor=="Carpet")] <- "carpet"
gcw$floor[which(gcw$floor=="Carreaux")] <- "tile"
gcw$floor[which(gcw$floor=="Carrelage")] <- "tile"
gcw$floor[which(gcw$floor=="cement")] <- "cement"
gcw$floor[which(gcw$floor=="Cement")] <- "cement"
gcw$floor[which(gcw$floor=="cement tiles")] <- "cement"
gcw$floor[which(gcw$floor=="cement/ tile")] <- "cement / tile"
gcw$floor[which(gcw$floor=="cement/brick")] <- "cement / bricks"
gcw$floor[which(gcw$floor=="Cement/brick")] <- "cement / bricks"
gcw$floor[which(gcw$floor=="Cement/concrete/terrazo")] <- "cement"
gcw$floor[which(gcw$floor=="cement/gravel")] <- "cement"
gcw$floor[which(gcw$floor=="Cemento")] <- "cement"
gcw$floor[which(gcw$floor=="Cemento(lujado o no)")] <- "cement"
gcw$floor[which(gcw$floor=="Cements")] <- "cement"
gcw$floor[which(gcw$floor=="CerÃ¡mica")] <- "ceramic tile"
gcw$floor[which(gcw$floor=="ceramic / mosaic / tiles")] <- "ceramic tile"
gcw$floor[which(gcw$floor=="ceramic tiles")] <- "ceramic tile"
gcw$floor[which(gcw$floor=="Ceramic tiles")] <- "ceramic tile"
gcw$floor[which(gcw$floor=="ceramic tiles, vinyl, bricks")] <- "ceramic tile / vinyl / brick"
gcw$floor[which(gcw$floor=="Ceramic tiles/stone tile")] <- "ceramic tile / stone tile"
gcw$floor[which(gcw$floor=="Ceramic tiles/Terazzo")] <- "ceramic tile / stone tile"
gcw$floor[which(gcw$floor=="ceramic/marble tiles")] <- "ceramic tile /marble tile"
gcw$floor[which(gcw$floor=="ceramic/marble/granite")] <- "ceramic tile /marble tile"
gcw$floor[which(gcw$floor=="ceramic/marble/porcelain tiles / terrazo")] <- "ceramic tile /marble tile"
gcw$floor[which(gcw$floor=="ceramic/terrazzo tiles")] <- "ceramic tile / stone tile"
gcw$floor[which(gcw$floor=="Cerámica")] <- "ceramic tile"
gcw$floor[which(gcw$floor=="Ciment")] <- "cement"
gcw$floor[which(gcw$floor=="clay / sand")] <- "clay"
gcw$floor[which(gcw$floor=="Concret")] <- "concrete"
gcw$floor[which(gcw$floor=="Concrete")] <- "concrete"
gcw$floor[which(gcw$floor=="Concrete, cement")] <- "concrete / cement"
gcw$floor[which(gcw$floor=="Concrete, vinyl/ asphalt strips")] <- "concete"
gcw$floor[which(gcw$floor=="Coral")] <- "coral"
gcw$floor[which(gcw$floor=="Dalle de sol")] <- "paving stone"
gcw$floor[which(gcw$floor=="dirt, clay")] <- "dirt"
gcw$floor[which(gcw$floor=="Dirt/Tapia")] <- "dirt"
gcw$floor[which(gcw$floor=="dung")] <- "dung"
gcw$floor[which(gcw$floor=="Dung")] <- "dung"
gcw$floor[which(gcw$floor=="Durawall Panel")] <- "durawall panel"
gcw$floor[which(gcw$floor=="earth")] <- "dirt"
gcw$floor[which(gcw$floor=="Earth (terra batida)")] <- "dirt"
gcw$floor[which(gcw$floor=="Earth (terra n?o batida)")] <- "dirt"
gcw$floor[which(gcw$floor=="Earth / sand")] <- "dirt"
gcw$floor[which(gcw$floor=="Earth / Sand")] <- "dirt"
gcw$floor[which(gcw$floor=="earth, sand")] <- "dirt"
gcw$floor[which(gcw$floor=="Earth, sand")] <- "dirt"
gcw$floor[which(gcw$floor=="Earth/ Sand (Dirt)")] <- "dirt"
gcw$floor[which(gcw$floor=="earth/mud/dung")] <- "dirt / dung"
gcw$floor[which(gcw$floor=="earth/sand")] <- "dirt"
gcw$floor[which(gcw$floor=="Earth/sand")] <- "dirt"
gcw$floor[which(gcw$floor=="Earth/Sand")] <- "dirt"
gcw$floor[which(gcw$floor=="earth/sand/clay")] <- "dirt"
gcw$floor[which(gcw$floor=="Earth/sand/clay")] <- "dirt"
gcw$floor[which(gcw$floor=="Earth/Sand/Mud")] <- "dirt"
gcw$floor[which(gcw$floor=="Earthen/clay  floor")] <- "dirt"
gcw$floor[which(gcw$floor=="Enamelled tiles/ marble")] <- "ceramic tile /marble tile"
gcw$floor[which(gcw$floor=="floating house")] <- "floating house"
gcw$floor[which(gcw$floor=="Floor mat, linoleum, vinyl")] <- "tile / vinyl"
gcw$floor[which(gcw$floor=="Gerflex")] <- "gerflex"
gcw$floor[which(gcw$floor=="granite / marble / ceramic")] <- "ceramic tile /marble tile"
gcw$floor[which(gcw$floor=="Granite, ceramic tiles")] <- "ceramic tile /marble tile"
gcw$floor[which(gcw$floor=="Half cement/mortar, half wood")] <- "cement / wood"
gcw$floor[which(gcw$floor=="Kashi tiles (Mosaic,Marble and Ceramic tiles)")] <- "ceramic tile /marble tile"
gcw$floor[which(gcw$floor=="Laminat")] <- "tile / vinyl"
gcw$floor[which(gcw$floor=="Laminate")] <- "tile / vinyl"
gcw$floor[which(gcw$floor=="Linoleum")] <- "tile / vinyl"
gcw$floor[which(gcw$floor=="linoleum/rubber carpet")] <- "tile / vinyl"
gcw$floor[which(gcw$floor=="Madera")] <- "wood"
gcw$floor[which(gcw$floor=="Manquant")] <- "NA"
gcw$floor[which(gcw$floor=="marble")] <- "ceramic tile /marble tile"
gcw$floor[which(gcw$floor=="Marble")] <- "ceramic tile /marble tile"
gcw$floor[which(gcw$floor=="marble, ceramic tile")] <- "ceramic tile /marble tile"
gcw$floor[which(gcw$floor=="Marley/ linoleum")] <- "tile / vinyl"
gcw$floor[which(gcw$floor=="Marley/Linoleum")] <- "tile / vinyl"
gcw$floor[which(gcw$floor=="Mat")] <- "mat"
gcw$floor[which(gcw$floor=="Materiales plÃ¡sticos o de Vinilo")] <- "tile / vinyl"
gcw$floor[which(gcw$floor=="Missing")] <- "NA"
gcw$floor[which(gcw$floor=="Moquette")] <- "carpet"
gcw$floor[which(gcw$floor=="mosaic or tile")] <- "mosaic or tile"
gcw$floor[which(gcw$floor=="Mosaico o terrazo")] <- "mosaic or tile"
gcw$floor[which(gcw$floor=="mud/clay")] <- "dirt"
gcw$floor[which(gcw$floor=="NA")] <- "NA"
gcw$floor[which(gcw$floor=="Natural floor")] <- "dirt"
gcw$floor[which(gcw$floor=="Natural floor mud/earth")] <- "dirt"
gcw$floor[which(gcw$floor=="other")] <- "other"
gcw$floor[which(gcw$floor=="Other")] <- "other"
gcw$floor[which(gcw$floor=="OTHER")] <- "other"
gcw$floor[which(gcw$floor=="Otro")] <- "other"
gcw$floor[which(gcw$floor=="Palm / Bamboo")] <- "palm / bamboo"
gcw$floor[which(gcw$floor=="palm, bamboo")] <- "palm / bamboo"
gcw$floor[which(gcw$floor=="Palm, bamboo")] <- "palm / bamboo"
gcw$floor[which(gcw$floor=="palm, bamboo, leeds")] <- "palm / bamboo"
gcw$floor[which(gcw$floor=="palm/bamboo")] <- "palm / bamboo"
gcw$floor[which(gcw$floor=="Palm/bamboo")] <- "palm / bamboo"
gcw$floor[which(gcw$floor=="palm/bambou")] <- "palm / bamboo"
gcw$floor[which(gcw$floor=="Palm/bambou")] <- "palm / bamboo"
gcw$floor[which(gcw$floor=="Palmera / BambÃº")] <- "palm / bamboo"
gcw$floor[which(gcw$floor=="Palmes/bambou")] <- "palm / bamboo"
gcw$floor[which(gcw$floor=="Parket")] <- "parquet"
gcw$floor[which(gcw$floor=="Parque ou bois ciré")] <- "parquet"
gcw$floor[which(gcw$floor=="parquet")] <- "parquet"
gcw$floor[which(gcw$floor=="Parquet")] <- "parquet"
gcw$floor[which(gcw$floor=="parquet / wood polished")] <- "parquet"
gcw$floor[which(gcw$floor=="Parquet o madera lustrada")] <- "parquet"
gcw$floor[which(gcw$floor=="Parquet or bois cire")] <- "parquet"
gcw$floor[which(gcw$floor=="Parquet or polished wood")] <- "parquet"
gcw$floor[which(gcw$floor=="parquet or polished wood")] <- "parquet"
gcw$floor[which(gcw$floor=="Parquet or Polished wood")] <- "parquet"
gcw$floor[which(gcw$floor=="Parquet ou bois cirÃ©")] <- "parquet"
gcw$floor[which(gcw$floor=="parquet, polished wood")] <- "parquet"
gcw$floor[which(gcw$floor=="Parquet, polished wood")] <- "parquet"
gcw$floor[which(gcw$floor=="parquet/polished wood")] <- "parquet"
gcw$floor[which(gcw$floor=="Pierre")] <- "stone"
gcw$floor[which(gcw$floor=="Piso de tierra")] <- "dirt"
gcw$floor[which(gcw$floor=="plain tile")] <- "tile"
gcw$floor[which(gcw$floor=="Planche en bois")] <- "planks / shingles"
gcw$floor[which(gcw$floor=="Planches en bois")] <- "planks / shingles"
gcw$floor[which(gcw$floor=="Planks/shingles")] <- "planks / shingles"
gcw$floor[which(gcw$floor=="plaster")] <- "plaster"
gcw$floor[which(gcw$floor=="Plastic")] <- "tile / vinyl"
gcw$floor[which(gcw$floor=="Plywood")] <- "plywood"
gcw$floor[which(gcw$floor=="Polished wood")] <- "parquet"
gcw$floor[which(gcw$floor=="Polished wood (laminate)")] <- "parquet"
gcw$floor[which(gcw$floor=="polished wood, parquet")] <- "parquet"
gcw$floor[which(gcw$floor=="Reed")] <- "palm / bamboo"
gcw$floor[which(gcw$floor=="Reeds")] <- "palm / bamboo"
gcw$floor[which(gcw$floor=="Rexine")] <- "rexine"
gcw$floor[which(gcw$floor=="Rudimentary floor")] <- "dirt"
gcw$floor[which(gcw$floor=="rug, carpet")] <- "carpet"
gcw$floor[which(gcw$floor=="sand and dung")] <- "dung"
gcw$floor[which(gcw$floor=="stone")] <- "stone"
gcw$floor[which(gcw$floor=="stones")] <- "stone"
gcw$floor[which(gcw$floor=="tablets / wood planks")] <- "planks / shingles"
gcw$floor[which(gcw$floor=="Tablones de madera")] <- "planks / shingles"
gcw$floor[which(gcw$floor=="Terre / Sable")] <- "dirt"
gcw$floor[which(gcw$floor=="Terre battue/ Sable")] <- "dirt"
gcw$floor[which(gcw$floor=="Terre/sable")] <- "dirt"
gcw$floor[which(gcw$floor=="Tierra / Arena")] <- "dirt"
gcw$floor[which(gcw$floor=="tile")] <- "tile"
gcw$floor[which(gcw$floor=="Tiles (Balady)")] <- "tile"
gcw$floor[which(gcw$floor=="Tiles/ bricks")] <- "tile"
gcw$floor[which(gcw$floor=="Tiles/marble")] <- "marble tile"
gcw$floor[which(gcw$floor=="tiles/terrazzo")] <- "tile / vinyl"
gcw$floor[which(gcw$floor=="Vinly or Asphalt strips")] <- "tile / vinyl"
gcw$floor[which(gcw$floor=="vinyl")] <- "tile / vinyl"
gcw$floor[which(gcw$floor=="Vinyl or aspalt strips")] <- "tile / vinyl"
gcw$floor[which(gcw$floor=="Vinyl or asphalt strip")] <- "tile / vinyl"
gcw$floor[which(gcw$floor=="vinyl or asphalt strips")] <- "tile / vinyl"
gcw$floor[which(gcw$floor=="Vinyl or asphalt strips")] <- "tile / vinyl"
gcw$floor[which(gcw$floor=="vinyl tile/vinyl carpet")] <- "tile / vinyl"
gcw$floor[which(gcw$floor=="Vinyl tiles")] <- "tile / vinyl"
gcw$floor[which(gcw$floor=="vinyl, asphalt strips")] <- "tile / vinyl"
gcw$floor[which(gcw$floor=="Vinyl, asphalt strips")] <- "tile / vinyl"
gcw$floor[which(gcw$floor=="vinyl/pvc or asphalt strips")] <- "tile / vinyl"
gcw$floor[which(gcw$floor=="Vinyle ou asphalte")] <- "tile / vinyl"
gcw$floor[which(gcw$floor=="wall to wall carpet")] <- "carpet"
gcw$floor[which(gcw$floor=="wood")] <- "wood"
gcw$floor[which(gcw$floor=="Wood")] <- "wood"
gcw$floor[which(gcw$floor=="Wood plank")] <- "planks / shingles"
gcw$floor[which(gcw$floor=="wood planks")] <- "planks / shingles"
gcw$floor[which(gcw$floor=="Wood planks")] <- "planks / shingles"
gcw$floor[which(gcw$floor=="Wood planks (non whittled)")] <- "planks / shingles"
gcw$floor[which(gcw$floor=="wood/plank")] <- "planks / shingles"
gcw$floor[which(gcw$floor=="woolen carpets/ synthetic carpet")] <- "carpet"

gcw$toilets[which(gcw$toilets=="11")] <- "11"
gcw$toilets[which(gcw$toilets=="12")] <- "12"
gcw$toilets[which(gcw$toilets=="13")] <- "13"
gcw$toilets[which(gcw$toilets=="14")] <- "14"
gcw$toilets[which(gcw$toilets=="15")] <- "15"
gcw$toilets[which(gcw$toilets=="21")] <- "21"
gcw$toilets[which(gcw$toilets=="22")] <- "22"
gcw$toilets[which(gcw$toilets=="23")] <- "23"
gcw$toilets[which(gcw$toilets=="24")] <- "24"
gcw$toilets[which(gcw$toilets=="31")] <- "31"
gcw$toilets[which(gcw$toilets=="41")] <- "41"
gcw$toilets[which(gcw$toilets=="42")] <- "42"
gcw$toilets[which(gcw$toilets=="43")] <- "43"
gcw$toilets[which(gcw$toilets=="44")] <- "44"
gcw$toilets[which(gcw$toilets=="45")] <- "45"
gcw$toilets[which(gcw$toilets=="51")] <- "51"
gcw$toilets[which(gcw$toilets=="96")] <- "96"
gcw$toilets[which(gcw$toilets=="99")] <- "99"
gcw$toilets[which(gcw$toilets=="Letrina (pozo negro, hueco con descarga de agua)")] <- "black pit latrine with water discharge"
gcw$toilets[which(gcw$toilets=="Balde")] <- "bucket toilet"
gcw$toilets[which(gcw$toilets=="Baldeo a otra parte")] <- "bucket toilet"
gcw$toilets[which(gcw$toilets=="Bucket")] <- "bucket toilet"
gcw$toilets[which(gcw$toilets=="bucket toilet")] <- "bucket toilet"
gcw$toilets[which(gcw$toilets=="Bucket toilet")] <- "bucket toilet"
gcw$toilets[which(gcw$toilets=="Seaux")] <- "bucket toilet"
gcw$toilets[which(gcw$toilets=="Composing toilet")] <- "composting toilet"
gcw$toilets[which(gcw$toilets=="composting toilet")] <- "composting toilet"
gcw$toilets[which(gcw$toilets=="Composting toilet")] <- "composting toilet"
gcw$toilets[which(gcw$toilets=="Inodoro de compostaje")] <- "composting toilet"
gcw$toilets[which(gcw$toilets=="Toilettes ? compostage")] <- "composting toilet"
gcw$toilets[which(gcw$toilets=="Toilettes a compostage")] <- "composting toilet"
gcw$toilets[which(gcw$toilets=="Toilettes à compostage")] <- "composting toilet"
gcw$toilets[which(gcw$toilets=="Connecte ? une fosse simple")] <- "connected to open pit"
gcw$toilets[which(gcw$toilets=="Double vault")] <- "Double vault"
gcw$toilets[which(gcw$toilets=="Eco sanitation")] <- "Eco sanitation"
gcw$toilets[which(gcw$toilets=="Inodoro con salida directa a acequia, zanja, río o estero")] <- "flush to ditch, river or estuary"
gcw$toilets[which(gcw$toilets=="Chasse branchee a latrines")] <- "flush to latrine"
gcw$toilets[which(gcw$toilets=="Chasse reliée à des latrines")] <- "flush to latrine"
gcw$toilets[which(gcw$toilets=="flust to pipe connected to canal")] <- "flush to pipe connected to canal"
gcw$toilets[which(gcw$toilets=="flush to pipe connected to ground water")] <- "flush to pipe connected to ground water"
gcw$toilets[which(gcw$toilets=="flush - to piped sewer system")] <- "flush to piped sewer system"
gcw$toilets[which(gcw$toilets=="flush to piped sewer system")] <- "flush to piped sewer system"
gcw$toilets[which(gcw$toilets=="Flush to piped sewer system")] <- "flush to piped sewer system"
gcw$toilets[which(gcw$toilets=="Flush/pour flush: Flush to piped sewer system")] <- "flush to piped sewer system"
gcw$toilets[which(gcw$toilets=="Inodoro conectado a fosa sÃ©ptica o pozo impermeable")] <- "flush to piped sewer system"
gcw$toilets[which(gcw$toilets=="Inodoro conectado a red de saneamiento")] <- "flush to piped sewer system"
gcw$toilets[which(gcw$toilets=="Inodoro conectado al alcantarillado")] <- "flush to piped sewer system"
gcw$toilets[which(gcw$toilets=="piped sewage system")] <- "flush to piped sewer system"
gcw$toilets[which(gcw$toilets=="toilet connected to sewer")] <- "flush to piped sewer system"
gcw$toilets[which(gcw$toilets=="flush - to pit latrine")] <- "flush to pit latrine"
gcw$toilets[which(gcw$toilets=="Flush to pit (latrine)")] <- "flush to pit latrine"
gcw$toilets[which(gcw$toilets=="flush to pit latrine")] <- "flush to pit latrine"
gcw$toilets[which(gcw$toilets=="Flush to pit latrine")] <- "flush to pit latrine"
gcw$toilets[which(gcw$toilets=="Flush/pour flush: Flush to pit (latrine)")] <- "flush to pit latrine"
gcw$toilets[which(gcw$toilets=="Chasse branchee a fosse septique")] <- "flush to septic tank"
gcw$toilets[which(gcw$toilets=="Chasse connectee ? fosse septique")] <- "flush to septic tank"
gcw$toilets[which(gcw$toilets=="Chasse connectée à fosse septique")] <- "flush to septic tank"
gcw$toilets[which(gcw$toilets=="flush - to septic tank")] <- "flush to septic tank"
gcw$toilets[which(gcw$toilets=="flush to septic tank")] <- "flush to septic tank"
gcw$toilets[which(gcw$toilets=="Flush to septic tank")] <- "flush to septic tank"
gcw$toilets[which(gcw$toilets=="Flush/pour flush: Flush to septic tank")] <- "flush to septic tank"
gcw$toilets[which(gcw$toilets=="Inodoro conectado al tanque séptico")] <- "flush to septic tank"
gcw$toilets[which(gcw$toilets=="septic tank")] <- "flush to septic tank"
gcw$toilets[which(gcw$toilets=="Flush to septic tank (with soak pit)")] <- "Flush to septic tank (with soak pit)"
gcw$toilets[which(gcw$toilets=="Flush to septic tank(Without soak pit)")] <- "Flush to septic tank(Without soak pit)"
gcw$toilets[which(gcw$toilets=="toilet connected to septic well")] <- "flush to septic well"
gcw$toilets[which(gcw$toilets=="Chasse branchee a l'egout")] <- "flush to sewer"
gcw$toilets[which(gcw$toilets=="Chasse connectee ? syst?me d'egouts")] <- "flush to sewer"
gcw$toilets[which(gcw$toilets=="Chasse connectée à système d'égouts")] <- "flush to sewer"
gcw$toilets[which(gcw$toilets=="Chasse branchee a autre chose")] <- "flush to somewhere else"
gcw$toilets[which(gcw$toilets=="Chasse reliée à autre chose")] <- "flush to somewhere else"
gcw$toilets[which(gcw$toilets=="flush - to somewhere else")] <- "flush to somewhere else"
gcw$toilets[which(gcw$toilets=="flush to somewhere else")] <- "flush to somewhere else"
gcw$toilets[which(gcw$toilets=="Flush to somewhere else")] <- "flush to somewhere else"
gcw$toilets[which(gcw$toilets=="Flush/pour flush: Flush to somewhere else")] <- "flush to somewhere else"
gcw$toilets[which(gcw$toilets=="Inodoro o taza turca (letrina) conectado/a a pozo permeable (perdedor)")] <- "flush to somewhere else"
gcw$toilets[which(gcw$toilets=="flush to vault (bayara)")] <- "flush to vault"
gcw$toilets[which(gcw$toilets=="Flush to well/pit (latrine)")] <- "Flush to well/pit (latrine)"
gcw$toilets[which(gcw$toilets=="Flush toilet")] <- "flush toilet"
gcw$toilets[which(gcw$toilets=="Chasse reliee ? endroit inconnu / Pas s?r / NSP o?")] <- "flush, don't know where"
gcw$toilets[which(gcw$toilets=="Chasse reliée à endroit inconnu / Pas sûr / NSP où")] <- "flush, don't know where"
gcw$toilets[which(gcw$toilets=="flush - don't know where")] <- "flush, don't know where"
gcw$toilets[which(gcw$toilets=="Flush to unknown place / Not sure / DK where")] <- "flush, don't know where"
gcw$toilets[which(gcw$toilets=="Flush to unknown place/not sure/DK where")] <- "flush, don't know where"
gcw$toilets[which(gcw$toilets=="flush, don't know where")] <- "flush, don't know where"
gcw$toilets[which(gcw$toilets=="Flush, don't know where")] <- "flush, don't know where"
gcw$toilets[which(gcw$toilets=="Toilet without flush, don't know where")] <- "flush, don't know where"
gcw$toilets[which(gcw$toilets=="water flow do not know where")] <- "flush, don't know where"
gcw$toilets[which(gcw$toilets=="Hanging toilet, Hanging latrine")] <- "hanging toilet/latrine"
gcw$toilets[which(gcw$toilets=="hanging toilet/latrine")] <- "hanging toilet/latrine"
gcw$toilets[which(gcw$toilets=="Hanging toilet/latrine")] <- "hanging toilet/latrine"
gcw$toilets[which(gcw$toilets=="Inodoro colgante, Letrina colgante")] <- "hanging toilet/latrine"
gcw$toilets[which(gcw$toilets=="Toilette suspendues/latrines suspendues")] <- "hanging toilet/latrine"
gcw$toilets[which(gcw$toilets=="Toilettes / Latrines suspendues")] <- "hanging toilet/latrine"
gcw$toilets[which(gcw$toilets=="Toilettes / Latrines suspendues avec dalle")] <- "hanging toilet/latrine"
gcw$toilets[which(gcw$toilets=="Toilettes/latrines suspendues sans dalle")] <- "hanging toilet/latrine"
gcw$toilets[which(gcw$toilets=="Inside dwelling")] <- "inside dwelling"
gcw$toilets[which(gcw$toilets=="latrine")] <- "latrine"
gcw$toilets[which(gcw$toilets=="Latrine (ciego o negro)")] <- "latrine (blind or black)"
gcw$toilets[which(gcw$toilets=="Latrine over river/lake")] <- "Latrine over river/lake"
gcw$toilets[which(gcw$toilets=="latrine with manual flush")] <- "latrine with manual flush"
gcw$toilets[which(gcw$toilets=="Long drop latrine")] <- "Long drop latrine"
gcw$toilets[which(gcw$toilets=="Manquant")] <- "NA"
gcw$toilets[which(gcw$toilets=="Missing")] <- "NA"
gcw$toilets[which(gcw$toilets=="NA")] <- "NA"
gcw$toilets[which(gcw$toilets=="No facilities or bush or field")] <- "No facility,Bush, Field"
gcw$toilets[which(gcw$toilets=="No facility, Bush, Field")] <- "No facility,Bush, Field"
gcw$toilets[which(gcw$toilets=="No facility,Bush, Field")] <- "No facility,Bush, Field"
gcw$toilets[which(gcw$toilets=="no facility/bush/field")] <- "No facility,Bush, Field"
gcw$toilets[which(gcw$toilets=="No facility/bush/field")] <- "No facility,Bush, Field"
gcw$toilets[which(gcw$toilets=="No hay instalaciÃ³n sanitaria, va al monte, campo")] <- "No facility,Bush, Field"
gcw$toilets[which(gcw$toilets=="No hay instalación sanitaria, va al monte, campo")] <- "No facility,Bush, Field"
gcw$toilets[which(gcw$toilets=="No service")] <- "No facility,Bush, Field"
gcw$toilets[which(gcw$toilets=="no toilet facility")] <- "No facility,Bush, Field"
gcw$toilets[which(gcw$toilets=="Pas de toilettes ou brousse ou champ")] <- "No facility,Bush, Field"
gcw$toilets[which(gcw$toilets=="Pas de toilettes, nature")] <- "No facility,Bush, Field"
gcw$toilets[which(gcw$toilets=="yard/bush/forest")] <- "No facility,Bush, Field"
gcw$toilets[which(gcw$toilets=="no facility/bush/field/beach")] <- "no facility/bush/field/beach"
gcw$toilets[which(gcw$toilets=="Autre")] <- "other"
gcw$toilets[which(gcw$toilets=="Autres")] <- "other"
gcw$toilets[which(gcw$toilets=="other")] <- "other"
gcw$toilets[which(gcw$toilets=="Other")] <- "other"
gcw$toilets[which(gcw$toilets=="OTHER")] <- "other"
gcw$toilets[which(gcw$toilets=="other place")] <- "other"
gcw$toilets[which(gcw$toilets=="Otro")] <- "other"
gcw$toilets[which(gcw$toilets=="Outside dwelling")] <- "Outside dwelling"
gcw$toilets[which(gcw$toilets=="pit")] <- "pit latrine"
gcw$toilets[which(gcw$toilets=="pit latrine")] <- "pit latrine"
gcw$toilets[which(gcw$toilets=="traditional latrine")] <- "pit latrine"
gcw$toilets[which(gcw$toilets=="traditional pit toilet")] <- "pit latrine"
gcw$toilets[which(gcw$toilets=="Pit latrine with non-washable slab*")] <- "Pit latrine with non-washable slab"
gcw$toilets[which(gcw$toilets=="covered pit latrine - with slab")] <- "pit latrine with slab"
gcw$toilets[which(gcw$toilets=="Latrine à trou avec dalle")] <- "pit latrine with slab"
gcw$toilets[which(gcw$toilets=="Latrines ? fosses avec dalle")] <- "pit latrine with slab"
gcw$toilets[which(gcw$toilets=="Latrines à fosse avec dalle")] <- "pit latrine with slab"
gcw$toilets[which(gcw$toilets=="Letrina de fosa con losa")] <- "pit latrine with slab"
gcw$toilets[which(gcw$toilets=="pit latrine - with slab")] <- "pit latrine with slab"
gcw$toilets[which(gcw$toilets=="pit latrine with slab")] <- "pit latrine with slab"
gcw$toilets[which(gcw$toilets=="Pit latrine with slab")] <- "pit latrine with slab"
gcw$toilets[which(gcw$toilets=="Pit latrine with washable slab*")] <- "pit latrine with slab"
gcw$toilets[which(gcw$toilets=="Pit latrine: Pit latrine with slab")] <- "pit latrine with slab"
gcw$toilets[which(gcw$toilets=="uncovered pit latrine - with slab")] <- "pit latrine with slab"
gcw$toilets[which(gcw$toilets=="without cement sink")] <- "pit latrine without slab"
gcw$toilets[which(gcw$toilets=="pit latrine - without slab / open pit")] <- "pit latrine without slab/open pit"
gcw$toilets[which(gcw$toilets=="uncovered pit latrine - without slab")] <- "pit latrine without slab/open pit"
gcw$toilets[which(gcw$toilets=="covered pit latrine - without slab / open pit")] <- "pit latrine without slab/open pit"
gcw$toilets[which(gcw$toilets=="Latrines ? fosse sans dalle / trou ouvert")] <- "pit latrine without slab/open pit"
gcw$toilets[which(gcw$toilets=="Latrines à fosse sans dalle / trou ouvert")] <- "pit latrine without slab/open pit"
gcw$toilets[which(gcw$toilets=="Latrines à trou sans dalle / trou ouvert")] <- "pit latrine without slab/open pit"
gcw$toilets[which(gcw$toilets=="Letrina de fosa sin losa / Foso abierto")] <- "pit latrine without slab/open pit"
gcw$toilets[which(gcw$toilets=="Pit latrine without slab / Open pit")] <- "pit latrine without slab/open pit"
gcw$toilets[which(gcw$toilets=="Pit latrine without slab /open pit")] <- "pit latrine without slab/open pit"
gcw$toilets[which(gcw$toilets=="pit latrine without slab/open pit")] <- "pit latrine without slab/open pit"
gcw$toilets[which(gcw$toilets=="Pit latrine without slab/open pit")] <- "pit latrine without slab/open pit"
gcw$toilets[which(gcw$toilets=="Pit latrine without slab/open pit*")] <- "pit latrine without slab/open pit"
gcw$toilets[which(gcw$toilets=="Pit latrine: Pit latrine without slab / Open pit")] <- "pit latrine without slab/open pit"
gcw$toilets[which(gcw$toilets=="private - with septic tank")] <- "private with septic tank"
gcw$toilets[which(gcw$toilets=="private - without septic tank")] <- "private without septic tank"
gcw$toilets[which(gcw$toilets=="River, canal")] <- "river, canal"
gcw$toilets[which(gcw$toilets=="river/stream/creek")] <- "river/stream/creek"
gcw$toilets[which(gcw$toilets=="Septic well")] <- "septic well"
gcw$toilets[which(gcw$toilets=="shared/public")] <- "shared/public"
gcw$toilets[which(gcw$toilets=="Single vault")] <- "single vault"
gcw$toilets[which(gcw$toilets=="slit latrine")] <- "slit latrine"
gcw$toilets[which(gcw$toilets=="toilet connected to plot/yard")] <- "toilet connected to plot/yard"
gcw$toilets[which(gcw$toilets=="traditional toilet to sea/river (low tide)")] <- "traditional toilet to sea/river (low tide)"
gcw$toilets[which(gcw$toilets=="Latrines ? fosses ventilees")] <- "Ventilated Improved Pit latrine (VIP)"
gcw$toilets[which(gcw$toilets=="Latrines ameliorees auto aerees (LAA)")] <- "Ventilated Improved Pit latrine (VIP)"
gcw$toilets[which(gcw$toilets=="Latrines améliorées ventilées (LAV)")] <- "Ventilated Improved Pit latrine (VIP)"
gcw$toilets[which(gcw$toilets=="Letrina de fosa mejorada con ventilación")] <- "Ventilated Improved Pit latrine (VIP)"
gcw$toilets[which(gcw$toilets=="pit latrine - ventilated improved pit (vip)")] <- "Ventilated Improved Pit latrine (VIP)"
gcw$toilets[which(gcw$toilets=="Pit latrine (UBVIP)")] <- "Ventilated Improved Pit latrine (VIP)"
gcw$toilets[which(gcw$toilets=="Pit latrine: Ventilated Improved Pit latrine (VIP)")] <- "Ventilated Improved Pit latrine (VIP)"
gcw$toilets[which(gcw$toilets=="ventilated improved (vip)")] <- "Ventilated Improved Pit latrine (VIP)"
gcw$toilets[which(gcw$toilets=="ventilated improved pit latrine (vip)")] <- "Ventilated Improved Pit latrine (VIP)"
gcw$toilets[which(gcw$toilets=="Ventilated Improved Pit latrine (VIP)")] <- "Ventilated Improved Pit latrine (VIP)"
gcw$toilets[which(gcw$toilets=="Ventilated latrine")] <- "Ventilated Improved Pit latrine (VIP)"
gcw$toilets[which(gcw$toilets=="cemented with sink")] <- "cemented with sink"


gcw$water[which(gcw$water=="NA")] <- NA
gcw$floor[which(gcw$floor=="NA")] <- NA
gcw$wall[which(gcw$wall=="NA")] <- NA
gcw$toilets[which(gcw$toilets=="NA")] <- NA

